---
name: Publish Docker Images
on:
  push:
    branches:
      - master
    paths:
      - haskell-ghc-all/*
      - haskell-ghc-amazon-linux/*
  schedule:
    - cron: "0 5 * * SUN"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

defaults:
  run:
    shell: bash

jobs:
  multiarch:
    uses: ./.github/workflows/reusable.yaml
    secrets: inherit
    with:
      context: haskell-ghc-all
      platforms: linux/arm64,linux/amd64
      runner_labels: "['self-hosted', 'futurice-jammy-16-core']"

  aws:
    uses: ./.github/workflows/reusable.yaml
    secrets: inherit
    with:
      context: haskell-ghc-amazon-linux
      platforms: linux/amd64
