---
on:
  workflow_call:
    inputs:
      context:
        type: string
        required: true
      platforms:
        type: string
        required: true
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    name: Build and Publish docker images
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compute tag
        run: if [[ ${{ github.event_name }} = 'schedule' ]]; then echo "tag=weekly" >> $GITHUB_OUTPUT; else echo "tag=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT; fi
        id: tag

      - name: Log in to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          platforms: ${{ inputs.platforms }}
          tags: futurice/base-images:${{ inputs.context }}-${{ steps.tag.outputs.tag }}
          push: true
