---
on:
  workflow_call:
    inputs:
      context:
        type: string
        required: true
      platforms:
        type: string
        required: true
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    name: Build and Publish docker images
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compute tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            futurice/base-images
          tags: |
            type=schedule,prefix=${{ inputs.context }}-,pattern=weekly
            type=raw,prefix=${{ inputs.context }}-,value={{date 'YYYYMMDD'}}

      - name: Log in to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          platforms: ${{ inputs.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
